languageCode = 'en-US'
title = 'xnacly - blog'

[[menus.main]]
name = '/'
pageRef = '/'
weight = 10

[[menus.main]]
name = '/archive'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = '/about'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

